### ISSUE TITLE
Feature Request: Plain Text Log

### ISSUE THREAD

**Issue by xnaas** [fspoesis/YoutubeChatArchiver#9]
Is it possible to get this to download just plain text log, or at least no PFPs at all (not even links to them)?

Thanks for the work on this so far btw, looks great!

**Comment by fspoesis** [comment]
Thanks! Anyhow, I just added support for a new plain text format. Please let me know if you have any issues

![example_plaintext](https://user-images.githubusercontent.com/29514995/89721380-5de3fe00-d9cc-11ea-9b4d-558380705368.png)
[example.txt](https://github.com/fspoesis/YoutubeChatArchiver/files/5046558/example.txt)

**Comment by xnaas** [comment]
Looks good, thanks. :)
